# TODO(josh): Migrate this to new benchmarking dag script

job = "Mach: Amazon670k"

[dataset]
train_data = "amazon-670k/train_shuffled_noHeader.txt"
test_data = "amazon-670k/test_shuffled_noHeader_sampled.txt"
format = "svm"
input_dim = 135909
max_test_batches = 20

[params]
learning_rate = 0.0001
epochs = 8
batch_size = 256

[mach]
num_classifiers = 3
max_label = 670091
hidden_layer_dim = 512
hidden_layer_sparsity = 1
last_layer_dim = 20000
last_layer_sparsity = 0.1
use_softmax = true