load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "bolt_lib",
    srcs = [
        "Config.cpp",
        "DataLoader.cpp",
        "DWTA.cpp",
        "HashTable.cpp",
        "Layer.cpp",
        "Network.cpp"
    ],
    hdrs = [
        "Config.h",
        "DataLoader.h",
        "DWTA.h",
        "HashTable.h",
        "Layer.h",
        "Network.h"
    ],
    visibility = ["//visibility:public"]
)