load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "UniversalHash",
    srcs = ["UniversalHash.cc"],
    hdrs = ["UniversalHash.h"],
    visibility = ["//visibility:public"],
)