
benchmarks:
  - Amazon Polarity 
  - Amazon670k Product Recommendation
  - Criteo DLRM 46M
  - Criteo DLRM 1M
  - MLM Fully Connected 
  - MLM Switch Layer 
  - Mnist 
mlflow:
  format: report_format.yaml
  report_format: null
  uri: http://thirdai:rwRp8GBNVplnLCIveMIz@ec2-184-73-150-35.compute-1.amazonaws.com
notion:
  # Page ID for the Notion page where benchmark results
  # are populated 
  page_id: cdaf6b03-6736-4633-be21-f0c9eb11dd81

  # Integration token
  token: secret_P3V9HcYuhZQ7YVIlxJFy0tJdNYVtx84078lFOIA4H2x

