run: 
  key: run_id
  values: 
    user_id: 
      alias: User 
      type: string 
      tag: info 
      description: ID of the user who ran the benchmark experiment 

    status:
      alias: Status 
      type: select 
      tag: info 
      description: Experiment status 
      options: 
        - FINISHED 
        - RUNNING 
        - FAILED 
        - KILLED 
        - UNFINISHED
        - SCHEDULED 

    start_time:
      alias: Start Time 
      type: timestamp 
      tag: info 
      description: The starting time of the experiment

    end_time:
      alias: End Time 
      type: timestamp
      tag: info 
      description: The end time of the experiment 

    # Logged metrics. A certain benchmark experiment 
    # might have different metrics, which will be automatically
    # added to the list of metrics reported
    train_loss: 
      alias: Train Loss 
      type: float 
      tag: metrics 
      description: Model's training loss 

    accuracy: 
      alias: Accuracy 
      type: float 
      tag: metrics 
      description: Model's accuracy 

    test_loss: 
      alias: Test Loss 
      type: float 
      tag: metrics 
      description: Model's test loss 

    batch_size: 
      alias: Batch Size 
      type: int 
      tag: params 
      description: Batch size 

    epochs: 
      alias: Epochs 
      type: int 
      tag: params 
      description: The number of epochs. 

    lr:
      alias: Learning Rate 
      type: float 
      tag: params 
      description: Model's learning rate 

    mlflow.runName:
      alias: Name 
      type: string 
      tag: tags 
      description: Name of the run 

    mlflow.note.content: 
      alias: Description
      type: string 
      tag: tags 
      description: Description of the run 

experiment:
  key: name 
  values: 
    name: 
      alias: name 
      type: str
      tag: info 
      description: Experiment name 
    
    experiment_id: 
      alias: experiment_id
      type: str 
      tag: info 
      description: Experiment ID 

order: 
  - Name 
  - User 
  - Start Time 
  - End Time 
  - Status 
  - Train Loss 
  - Accuracy
  - Test Loss 
  - Batch Size 
  - Description 
  - Learning Rate 
  - Epochs 

alias_table: 
  User: user_id 
  Status: status 
  Start Time: start_time 
  End Time: end_time 
  Train Loss: train_loss 
  Accuracy: accuracy 
  Test Loss: test_loss 
  Batch Size: batch_size 
  Epochs: epochs 
  Learning Rate: learning rate 
  Name: mlflow.runName 
  Description: mlflow.note.content 


    
