job = "Criteo DLRM"

[dataset]
train_data = "criteo-small/train_shuf.txt"
test_data = "criteo-small/test_shuf.txt"
dense_features = 15
categorical_features = 24

[params]
loss_fn = "MeanSquaredError"
train_metrics = []
test_metrics = ["categorical_accuracy"]
learning_rate = 0.001
epochs = 2
batch_size = 255
rehash = 3000
rebuild = 10000
use_auc = true

[embedding_layer]
num_embedding_lookups = 8
lookup_size = 16
log_embedding_block_size = 10

[[bottom_mlp_layers]]
dim = 1000
activation = 'ReLU'
sparsity = 0.2
hashes_per_table = 3
num_tables = 128
reservoir_size = 32
range_pow = 9

[[bottom_mlp_layers]]
dim = 100
activation = "ReLU"

[[top_mlp_layers]]
dim = 100
activation = "ReLU"

[[top_mlp_layers]]
dim = 1000
activation = 'ReLU'
sparsity = 0.2
hashes_per_table = 3
num_tables = 128
reservoir_size = 32
range_pow = 9

[[top_mlp_layers]]
dim = 1
activation = 'Linear'
