job = "intent fully connected network"

[dataset]
train_data = "/Users/nmeisburger/files/ThirdAI/data/intent/train_shuf.svm"
test_data = "/Users/nmeisburger/files/ThirdAI/data/intent/test_shuf.svm"
format = "svm"
input_dim = 5512

[params]
learning_rate = 0.001
epochs = 2
batch_size = 128
rehash = 3000
rebuild = 10000

[[layers]]
dim = 10000
activation = 'ReLU'
sparsity = 0.1
hashes_per_table = 4
num_tables = 64
reservoir_size = 32
range_pow = 12


[[layers]]
dim = 151
activation = 'Softmax'
