job = "Criteo DLRM"

[dataset]
train_data = "intent/train_shuf_criteo.txt"
test_data = "intent/test_shuf_criteo.txt"
dense_features = 512
categorical_features = 26

[params]
loss_fn = "CategoricalCrossEntropy"
train_metrics = []
test_metrics = ["categorical_accuracy"]
learning_rate = 0.001
epochs = 30
batch_size = 255
rehash = 5000
rebuild = 10000
use_auc = false

[embedding_layer]
num_embedding_lookups = 16
lookup_size = 16
log_embedding_block_size = 16

[[bottom_mlp_layers]]
dim = 10000
activation = 'ReLU'
sparsity = 0.2
hashes_per_table = 3
num_tables = 128
range_pow = 9
reservoir_size = 32

[[bottom_mlp_layers]]
dim = 250
activation = "ReLU"

[[top_mlp_layers]]
dim = 100
activation = "ReLU"

[[top_mlp_layers]]
dim = 10000
activation = 'ReLU'
sparsity = 0.2
hashes_per_table = 3
num_tables = 128
range_pow = 9
reservoir_size = 32

[[top_mlp_layers]]
dim = 151
activation = 'Softmax'
