job = "mnist sparse output layer"

[dataset]
train_data = "mnist/mnist"
test_data = "mnist/mnist.t"
format = "svm"
input_dim = 784

[params]
loss_fn = "CategoricalCrossEntropy"
train_metrics = []
test_metrics = ["categorical_accuracy"]
learning_rate = 0.0001
epochs = 2
batch_size = 250
rehash = 500
rebuild = 10000

[[layers]]
dim = 256
activation = 'ReLU'


[[layers]]
dim = 10
activation = 'Softmax'
sparsity = 0.4
hashes_per_table = 1
num_tables = 64
reservoir_size = 10
range_pow = 3
