job = "mnist dense layers"

[dataset]
train_data = "mnist/mnist"
test_data = "mnist/mnist.t"
format = "svm"
input_dim = 784

[params]
loss_fn = "CategoricalCrossEntropyLoss"
train_metrics = []
test_metrics = ["categorical_accuracy"]
learning_rate = 0.0001
epochs = 2
batch_size = 250
rehash = 10000000
rebuild = 10000000

[[layers]]
dim = 512
activation = 'ReLU'

[[layers]]
dim = 256
activation = 'ReLU'

[[layers]]
dim = 10
activation = 'Softmax'
