load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "bolt",
    srcs = [
        "bolt.cpp"
    ],
    deps = [
        "//Bolt/src:bolt_lib"
    ],
    visibility = ["//visibility:public"]
)