load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "utils",
    deps = [
        "//utils/dataset:dataset",
        "//utils/hashing:hashes"
    ],
    visibility = ["//visibility:public"],
)