name: benchmarks
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          ls -a
        host: 70.233.60.118
        user: alan
        key: ${{ secrets.PRIVATE_KEY}}