name: benchmarks
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bolt Benchmarks
      uses: fifsky/ssh-action@master
      with:
        command: |
          w
          bin/regular-benchmark.sh
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}