name: benchmarks

# Controls when the workflow will run
on:
  # Triggers the workflow on pushes to benchmark-tests branch
  push:
    branches: [ benchmark-tests ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Unit Tests
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd Universe
          git pull origin benchmark-tests
          bin/regular-benchmark.sh
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Copy log file
      run: |
        scp ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/logs/2021-09-29/log.html log.html
    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        command: |
          
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Optional (recommended): mail server username:
        username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
        subject: Github Actions job result
        # Required recipients' addresses:
        to: alan@thirdai.com
        # Required sender full name (address can be skipped):
        from: cicd@thirdai.com
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional plain body:
        body: Benchmark Results
        # Optional HTML body read from file:
        html_body: file://log.html
        # Optional carbon copy recipients:
        cc: abj3@rice.edu
        # Optional recipient of the email response:
        reply_to: cicd@thirdai.com
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: normal