name: benchmarks

# Controls when the workflow will run
on:
  # Triggers the workflow on pushes to benchmark-tests branch
  push:
    branches: [ benchmark-tests ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bolt Benchmarks
      uses: fifsky/ssh-action@master
      with:
        command: |
          rm -rf Universe
          git clone -b benchmark-tests --single-branch git@github.com:ThirdAILabs/Universe.git
          cd Universe
          bin/regular-benchmark.sh
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}