name: benchmarks

# Controls when the workflow will run
on:
  push:
    branches: [ benchmark-tests ]
  # Schedule for every day at 0,7,14,21 UTC
  schedule:
    - cron: '0 0,7,14,21 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Benchmark Tests
      uses: fifsky/ssh-action@master
      with:
        command: |
          git fetch
          echo "branch" ${GITHUB_REF##*/}
          cd Universe
          git pull origin benchmark-tests
          pip3 install .
          bin/regular-benchmark.sh
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}