name: benchmarks

# Controls when the workflow will run
on:
  push:
    branches: [ benchmark-tests ]
  # Schedule for every day at 0,7,14,21 UTC
  schedule:
    - cron: '0 0,7,14,21 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Run Benchmark Tests
      uses: fifsky/ssh-action@master
      with:
        command: |
          git fetch
          echo "branch" ${{ steps.extract_branch.outputs.branch }}

        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}