name: benchmarks

# Controls when the workflow will run
on:
  # Schedule for Thursday 4 PM CST (21:00 UTC)
  schedule:
  - cron: '0 0.1,2,3,4,5,6,7,21,22,23 * * 4'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: benchmark-tests
    - name: Run Benchmark Tests
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd Universe
          git pull origin benchmark-tests
          pip3 install .
          bin/regular-benchmark.sh
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
    # - name: Copy log file
    #   run: |
    #     mkdir -p ~/.ssh
    #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    #     chmod 600 ~/.ssh/id_rsa
    #     ssh-keyscan github.com >> ~/.ssh/known_hosts
    #     ssh -vT git@github.com
    #     scp ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/logs/2021-09-29/log.html ${{ github.workspace }}/log.html
    # - name: Send Email
    #   uses: dawidd6/action-send-mail@v3
    #   with:
    #     # Required mail server address:
    #     server_address: smtp.gmail.com
    #     # Required mail server port:
    #     server_port: 465
    #     # Optional (recommended): mail server username:
    #     username: ${{secrets.MAIL_USERNAME}}
    #     # Optional (recommended) mail server password:
    #     password: ${{secrets.MAIL_PASSWORD}}
    #     # Required mail subject:
    #     subject: Github Actions job result
    #     # Required recipients' addresses:
    #     to: alan@thirdai.com
    #     # Required sender full name (address can be skipped):
    #     from: cicd@thirdai.com
    #     # Optional whether this connection use TLS (default is true if server_port is 465)
    #     secure: true
    #     # Optional plain body:
    #     body: Benchmark Results
    #     # Optional HTML body read from file:
    #     html_body: file://log.html
    #     # Optional carbon copy recipients:
    #     cc: abj3@rice.edu
    #     # Optional recipient of the email response:
    #     reply_to: cicd@thirdai.com
    #     # Optional unsigned/invalid certificates allowance:
    #     ignore_cert: true
    #     # Optional converting Markdown to HTML (set content_type to text/html too):
    #     convert_markdown: true
    #     # Optional priority: 'high', 'normal' (default) or 'low'
    #     priority: normal