name: Train Bolt on MNIST

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
    # the rest of the steps
    - uses: actions/checkout@v2

    # This is needed to ensure code can build
    - name: Install MPI
      run: |
        sudo apt install -y mpich libmpich-dev
        sudo apt install -y openmpi-bin openmpi-doc libopenmpi-dev
    - name: Build ThirdAI Python Library
      run: |
        pip3 install .
    - name: Train Bolt
      run: |
        bin/bolt_mnist_test.sh
