name: Check Python and C++ Formatting

# Kills old jobs from the same pr if we push a new commit
# See https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
concurrency: 
  group: format-${{ github.head_ref }}
  cancel-in-progress: true

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cpp-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:           
        submodules: 'recursive'
        token: ${{ secrets.CICD_REPO_ACCESS_TOKEN }}
            
    - name: Run clang-format
      uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: '.'
        exclude: './deps'
        clangFormatVersion: 10
        style: file

  python-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Python
        run: |
          sudo pip3 install black
      - name: Check Python format 
        run: |
          black . --check --exclude /deps/
