name: Check Formatting

# Kills old jobs from the same pr if we push a new commit
# See https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cpp-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:           
        submodules: 'recursive'
        token: ${{ secrets.CICD_REPO_ACCESS_TOKEN }}
            
    - name: Run clang-format
      uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: '.'
        exclude: './deps'
        clangFormatVersion: 15
        style: file

  python-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Black
        run: |
          sudo pip3 install black
      - name: Prepare isort
        run: |
          sudo pip3 install isort
      - name: Check Black format 
        run: |
          black . --check --exclude "build|.venv|venv|.env|env|deps"
      - name: Check isort format
        run: |
          isort . --check --profile black --skip-glob deps --skip _deps

  cmake-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare cmake format
        run: |
          sudo pip3 install cmake-format
      - name: Check Cmake format
        run: |
          find . -name 'CMakeLists.txt' -o -name '*.cmake' | grep -v ./deps | xargs -I% cmake-format --check % 
