name: clang-format

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  clang-format-job:
    runs-on: ubuntu-latest
    steps:
    - name: Install clang-format 
      run: |
        sudo apt install clang-format
        clang-format --version
    - uses: actions/checkout@v2
    - name: Check format for all files in all directories
      run: |
        find ../ -iname '*.h' -o -iname '*.cc' | xargs clang-format -i -style=file
        git diff
        chmod +x "${GITHUB_WORKSPACE}/.github/clang-format.sh"
        "${GITHUB_WORKSPACE}/.github/clang-format.sh"