name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: AutoModality/action-clean@v1
    - uses: actions/checkout@v3
      with:           
        submodules: 'recursive'
        token: ${{ secrets.CICD_REPO_ACCESS_TOKEN }}
        fetch-depth: 0
    - name: Create venv
      run: |
          python -m venv ../old_thirdai
          source ../old_thirdai/bin/activate
          git checkout backwards-compatibility-benchmarks
          bin/build.py --extras test
          pip uninstall -y thirdai
    - name: Save old model versions
      run: |
          source ../old_thirdai/bin/activate
          versions=$(curl https://pypi.org/pypi/thirdai/json  | jq -r '.releases | keys | .[]')
          file_version=$(cat "thirdai.version")
          file_major_minor=$(echo "$file_version" | cut -d. -f1-2)
          filtered_versions=()
          for version in $versions; do
            major_minor=$(echo "$version" | cut -d. -f1-2)
            if [ "$major_minor" = "$file_major_minor" ]; then
              filtered_versions+=( $version )
            fi
          done
          for filtered_version in "${filtered_versions[@]}"; do
            echo $filtered_version
          done
          for filtered_version in "${filtered_versions[@]}"; do
            git checkout tags/v${filtered_version}
            bin/build.py
            git checkout backwards-compatibility-benchmarks
            python -m benchmarks_v2.src.runners.backward_compatibility_runners.save_old_models --runner udt temporal query_reformulation --version $filtered_version
          done
    - name: Run mini benchmarks with old models
      run: |
          python -m benchmarks_v2.src.main --runner backward_compatibility_udt
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3