name: Docker Integration Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker-integration:
    runs-on: ubuntu-latest
    steps:

      # See https://github.com/actions/checkout/issues/124
      # We need the actual branch name so that the archive building the image works
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: 'recursive'

      - uses: actions/checkout@v2
        if: github.event_name == 'push'
        with:
          fetch-depth: 0

      - name: Build and test the product Docker images
        run: docker/product/test_all_product_dockers.sh
