name: Lint C++ Code

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:           
          submodules: 'recursive'
          
      - name: Run clang-tidy linting on all files
        run: |
          docker build -t lint_image -f docker/develop/Dockerfile .  
          docker run --privileged --mount type=bind,source=${PWD},target=/src lint_image src/bin/lint.sh
