name: Run Python Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
      # the rest of the steps
      - uses: actions/checkout@v2

      - name: download-openmpi
        run: |
          sudo apt-get update
          sudo apt-get install gcc g++
          sudo apt-get install -y mpich libmpich-dev
          sudo apt-get install -y openmpi-bin openmpi-doc libopenmpi-dev
      - name: Prepare Python
        run: |
          sudo pip3 install pytest
          sudo pip3 install numpy
      - name: Build and Run Tests
        run: |
          bin/build.sh
          bin/python-test.sh
